INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('CS3001','Software Development','Jackson Ong',80);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS1000','Go Basic','Low Kheng Hian',25);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS1001','Database Management','Matthew Lee',80);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS1002','Go Advanced','Lee Ching Yun',23);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS1010','Operating System','Ken Tan',100);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS2001','Go In Action 1 ','Low Kheng Hian',22);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS2002','Go In Action 2','Lee Ching Yun',22);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS3001','Go Microservice 1','Lee Ching Yun',22);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS3002','Go Microservice 2','Low Kheng Hian',22);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('GOS4000','Go Live Project','Matthew Lee',50);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('IOT2000','Basic Automation','Ken Tan',100);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('IOT3000','Advanced Automation','Jackson Ong',50);
INSERT INTO Course (`CourseID`,`Title`,`Lecturer`,`ClassSize`) VALUES ('IOT4000','Industry 4.0','Michael Lim',150);